$(document).ready(function(){
  $("bio").click(function(){
    $(".bioPanel").slideDown("slow");
  });
  $("calcAB").click(function(){
    $(".calcABPanel").slideDown("slow");
  });
    $("calcBC").click(function(){
    $(".calcBCPanel").slideDown("slow");
  });
    $("chem").click(function(){
    $(".chemPanel").slideDown("slow");
  });
    $("comp").click(function(){
    $(".compPanel").slideDown("slow");
  });
    $("englang").click(function(){
    $(".englangPanel").slideDown("slow");
  });
    $("englit").click(function(){
    $(".englitPanel").slideDown("slow");
  });
    $("enviro").click(function(){
    $(".enviroPanel").slideDown("slow");
  });
    $("humangeo").click(function(){
    $(".humangeoPanel").slideDown("slow");
  });
    $("macro").click(function(){
    $(".macroPanel").slideDown("slow");
  });
    $("precalc").click(function(){
    $(".precalcPanel").slideDown("slow");
  });
    $("phys1").click(function(){
    $(".phys1Panel").slideDown("slow");
  });
    $("phys2").click(function(){
    $(".phys2Panel").slideDown("slow");
  });
    $("seminar").click(function(){
    $(".seminarPanel").slideDown("slow");
  });
    $("spanishlang").click(function(){
    $(".spanishlangPanel").slideDown("slow");
  });
    $("spanishlit").click(function(){
    $(".spanishlitPanel").slideDown("slow");
  });
    $("stat").click(function(){
    $(".statPanel").slideDown("slow");
  });
    $("2d").click(function(){
    $(".2dPanel").slideDown("slow");
  });
    $("drawing").click(function(){
    $(".drawingPanel").slideDown("slow");
  });
    $("usgov").click(function(){
    $(".usgovPanel").slideDown("slow");
  });
    $("ushist").click(function(){
    $(".ushistPanel").slideDown("slow");
  });
    $("world").click(function(){
    $(".worldPanel").slideDown("slow");
  });
  



  
});
