$(document).ready(function(){
  $("#bio").click(function(){
    $("#bioPanel").slideDown("slow");
  });
    $("#brawl").click(function(){
    $("#brawlPanel").slideDown("slow");
  });
    $("#calcAB").click(function(){
    $("#calcABPanel").slideDown("slow");
  });
    $("#calcBC").click(function(){
    $("#calcBCPanel").slideDown("slow");
  });
    $("#chem").click(function(){
    $("#chemPanel").slideDown("slow");
  });
    $("#compsci").click(function(){
    $("#compsciPanel").slideDown("slow");
  });
    $("#englang").click(function(){
    $("#englangPanel").slideDown("slow");
  });
    $("#englit").click(function(){
    $("#englitPanel").slideDown("slow");
  });
    $("#enviro").click(function(){
    $("#enviroPanel").slideDown("slow");
  });
    $("#human").click(function(){
    $("#humanPanel").slideDown("slow");
  });
    $("#macro").click(function(){
    $("#macroPanel").slideDown("slow");
  });
    $("#precalc").click(function(){
    $("#precalcPanel").slideDown("slow");
  });
    $("#phys1").click(function(){
    $("#phys1Panel").slideDown("slow");
  });
    $("#phys2").click(function(){
    $("#phys2Panel").slideDown("slow");
  });
    $("#semi").click(function(){
    $("#semiPanel").slideDown("slow");
  });
    $("#spanlang").click(function(){
    $("#spanlangPanel").slideDown("slow");
  });
    $("#spanlit").click(function(){
    $("#spanlitPanel").slideDown("slow");
  });
    $("#stat").click(function(){
    $("#statPanel").slideDown("slow");
  });
    $("#2d").click(function(){
    $("#2dPanel").slideDown("slow");
  });
    $("#draw").click(function(){
    $("#drawPanel").slideDown("slow");
  });
    $("#usgov").click(function(){
    $("#usgovPanel").slideDown("slow");
  });
    $("#ushist").click(function(){
    $("#ushistPanel").slideDown("slow");
  });
      $("#world").click(function(){
    $("#worldPanel").slideDown("slow");
  });
  
});
